# Generated by Django 5.1.1 on 2024-09-14 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='empID',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
