# Generated by Django 5.1.1 on 2024-09-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_remove_employee_empid_remove_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='empID',
            field=models.PositiveIntegerField(editable=False, null=True, unique=True),
        ),
    ]
